org.gradle.jvmargs=-Xms128m -Xmx1024m -XX:MaxMetaspaceSize=256m -XX:+UseSerialGC
kotlin.daemon.jvmargs=-Xms128m -Xmx512m
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
